install:
  - choco install gitversion.portable -pre -y

skip_tags: true

before_build:
  - ps: gitversion /l console /output buildserver  
  - ps: $env:GitVersion_InformationalVersion = $env:GitVersion_InformationalVersion.Replace('/', '-');
  - ps: $env:CustomVersion = "$env:GitVersion_InformationalVersion.$env:APPVEYOR_BUILD_NUMBER"
  - ps: $env:CustomFileVersion = "$env:GitVersion_MajorMinorPatch.$env:APPVEYOR_BUILD_NUMBER"
  - ps: Write-Host $env:CustomVersion
  - ps: Write-Host $env:CustomFileVersion 
  - dotnet restore .\src\Projector.sln

configuration: Release

build_script:
  - dotnet build .\src\Projector.sln

test_script:
  - dotnet test .\src\Projector.Data.Test/Projector.Data.Test.csproj

after_build:
  - dotnet pack --no-build .\src\Projector.Data -c Release /p:PackageVersion="%GitVersion_NuGetVersion%"

artifacts:
  - path: '**\*.nupkg'